org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.java.home=/home/user/jdk-21.0.2+13
org.gradle.parallel=false
github_repo=Mylittlestories/AuraPlay
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.workers.max=1
android.useAndroidX=true
android.enableJetifier=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx384m
